export const GET_MOVIES_NOWPLAYING = 'GET_MOVIES_NOWPLAYING';
export const GET_MOVIES_TOPRATED = 'GET_MOVIES_TOPRATED';
export const GET_MOVIES_UPCOMING = 'GET_MOVIES_UPCOMING';
export const GET_MOVIES_POPULAR = 'GET_MOVIES_POPULAR';
export const API_KEY = 'API_KEY';
